import React from 'react';
import './../config/base.css'

import BillActions from './BillActions';

export default {
  title: 'Compositions/Bill Actions',
  component: BillActions,
};

const Template = (args) => <BillActions {...args} />

export const Default = Template.bind({})
Default.args = {
  defaultState: {
    showMinorActions: false,
  },
  actions: [
    {
      description: 'Draft Request Received',
      date: '2018-12-03',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Fiscal Note Probable',
      date: '2019-01-29',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft to Requester for Review',
      date: '2019-02-19',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft to Requester for Review',
      date: '2019-02-19',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Legal Review',
      date: '2019-02-19',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Edit',
      date: '2019-02-19',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft to Drafter - Edit Review [KWK]',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Input/Proofing',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Final Drafter Review',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Bill Draft Text Available Electronically',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Executive Director Review',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Assembly',
      date: '2019-02-27',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Executive Director Final Review',
      date: '2019-02-28',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft Ready for Delivery',
      date: '2019-02-28',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft Back for Redo',
      date: '2019-03-08',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft to Requester for Review',
      date: '2019-03-11',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Legal Review',
      date: '2019-03-11',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft to Drafter - Edit Review [KWK]',
      date: '2019-03-11',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft in Final Drafter Review',
      date: '2019-03-12',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Bill Draft Text Available Electronically',
      date: '2019-03-12',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Executive Director Final Review',
      date: '2019-03-12',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Draft Delivered to Requester',
      date: '2019-03-12',
      chamber: null,
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Introduced',
      date: '2019-03-12',
      chamber: 'House',
      committee: null,
      vote: null,
      isMajor: true,
    },
    {
      description: 'Fiscal Note Requested',
      date: '2019-03-12',
      chamber: 'House',
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'Introduced Bill Text Available Electronically',
      date: '2019-03-12',
      chamber: 'House',
      committee: null,
      vote: null,
      isMajor: false,
    },
    {
      description: 'First Reading',
      date: '2019-03-13',
      chamber: 'House',
      committee: 'House Floor',
      vote: null,
      isMajor: true,
    },
    {
      description: 'Referred to Committee',
      date: '2019-03-14',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: null,
      isMajor: true,
    },
    {
      description: 'Hearing',
      date: '2019-03-20',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: null,
      isMajor: true,
    },
    {
      description: 'Fiscal Note Received',
      date: '2019-03-20',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: null,
      isMajor: false,
    },
    {
      description: 'Fiscal Note Signed',
      date: '2019-03-20',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: null,
      isMajor: false,
    },
    {
      description: 'Fiscal Note Printed',
      date: '2019-03-21',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: null,
      isMajor: false,
    },
    {
      description: 'Tabled in Committee',
      date: '2019-03-22',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: 'Unknown',
      isMajor: true,
    },
    {
      description: 'Missed Deadline for Revenue Bill Transmittal',
      date: '2019-04-01',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: false,
      isMajor: true,
    },
    {
      description: 'Died in Standing Committee',
      date: '2019-04-25',
      chamber: 'House',
      committee: 'House XXX Committee',
      vote: false,
      isMajor: true,
    }
  ],
}
